using System.Text;

namespace SchemaSyncApi;

// Turns a diff list into a real, reviewable T-SQL script — the user's own
// requirement: sync happens by generating a script, not by silently mutating
// the target. New nullable-mismatch columns are always added as NULL first
// (never NOT NULL) so the script can't fail against a table that already has
// rows; tightening to NOT NULL after a backfill is left as a deliberate manual
// follow-up, called out in the script's own comment.
public class ScriptGenerator
{
    public string Generate(List<DiffEntry> diffs, SchemaSnapshot source)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by SchemaSyncApi — review before running.");
        sb.AppendLine($"-- {diffs.Count} change(s) detected.");
        sb.AppendLine();

        var sourceTables = source.Tables.ToDictionary(t => t.Name, StringComparer.OrdinalIgnoreCase);

        foreach (var table in diffs.Select(d => d.TableName).Distinct())
        {
            var tableDiffs = diffs.Where(d => d.TableName == table).ToList();
            var missingTable = tableDiffs.FirstOrDefault(d => d.Kind == DiffKind.MissingTable);

            if (missingTable is not null)
            {
                sb.AppendLine(GenerateCreateTable(sourceTables[table]));
                sb.AppendLine("GO");
                sb.AppendLine();
                continue;
            }

            foreach (var diff in tableDiffs.Where(d => d.Kind == DiffKind.MissingColumn))
            {
                var column = sourceTables[table].Columns.First(c => c.Name == diff.ColumnName);
                sb.AppendLine($"-- {diff.Description}");
                sb.AppendLine($"ALTER TABLE dbo.[{table}] ADD [{column.Name}] {column.SqlTypeExpression()} NULL;");
                sb.AppendLine("GO");
                sb.AppendLine();
            }

            foreach (var diff in tableDiffs.Where(d => d.Kind == DiffKind.ColumnTypeMismatch))
            {
                var column = sourceTables[table].Columns.First(c => c.Name == diff.ColumnName);
                sb.AppendLine($"-- {diff.Description}");
                sb.AppendLine($"ALTER TABLE dbo.[{table}] ALTER COLUMN [{column.Name}] {column.SqlTypeExpression()} " +
                              $"{(column.IsNullable ? "NULL" : "NOT NULL")};");
                sb.AppendLine("GO");
                sb.AppendLine();
            }

            foreach (var diff in tableDiffs.Where(d => d.Kind == DiffKind.ColumnNullabilityMismatch))
            {
                var column = sourceTables[table].Columns.First(c => c.Name == diff.ColumnName);
                sb.AppendLine($"-- {diff.Description}");
                sb.AppendLine($"-- NOTE: widening to NULL regardless of source's nullability, to avoid failing " +
                              $"on existing rows. Tighten to NOT NULL manually after backfilling if the source requires it.");
                sb.AppendLine($"ALTER TABLE dbo.[{table}] ALTER COLUMN [{column.Name}] {column.SqlTypeExpression()} NULL;");
                sb.AppendLine("GO");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static string GenerateCreateTable(TableInfo table)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"CREATE TABLE dbo.[{table.Name}] (");

        var columnLines = table.Columns
            .OrderBy(c => c.OrdinalPosition)
            .Select(c =>
            {
                var identity = c.IsIdentity ? " IDENTITY" : "";
                var nullability = c.IsNullable ? "NULL" : "NOT NULL";
                return $"    [{c.Name}] {c.SqlTypeExpression()}{identity} {nullability}";
            });

        sb.AppendLine(string.Join(",\n", columnLines));
        sb.Append(");");
        return sb.ToString();
    }
}
